services:

  web:
    image: likely/frontend
    build:
      context: ./frontend
    restart: unless-stopped
    container_name: likely-web
    ports:
      - '8080:80'
    depends_on:
      - server

  server:
    image: likely/backend
    build:
      context: ./backend
    restart: unless-stopped
    container_name: likely-server
    ports:
      - '3000:3000'
    depends_on:
      - database

  database:
    image: likely/mongo
    build:
      context: ./database
    restart: unless-stopped
    container_name: likely-db
    volumes:
      - likelydb:/data/db
    env_file:
      - ./env/mongo.env
    ports:
      - '27017:27017'

volumes:
  likelydb: