FROM mongo:7.0.0

LABEL author="Kevin Kouomeu"
LABEL version="1.0"
LABEL description="Likely database"

ENV MONGO_INITDB_DATABASE likely
ENV MONGO_INITDB_ROOT_USERNAME root
ENV MONGO_INITDB_ROOT_PASSWORD root-pwd

EXPOSE 27017