# Use root/example as user/password credentials
services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root-pwd
    ports:
     - 27017:27017
